---
title: "Proyecto"
author: 
  - Luis Fernando Amey Apuy - C20470
  - Fabián Brenes Thomas - C21380
  - Marco Antonio Guardia Ortiz - C23521
  - Anthony Mauricio Jiménez Navarro - C24067
  - Laura Jimena Villacís Delgado - C28386
date: "2024-05-13"
output: 
  rmdformats::downcute:
    default_style: "dark"
    downcute_theme: "chaos"
---


```{r}
library(readxl)
library(tidyverse)
ABC <- read_excel("Base de datos.xlsx")
SUPEN <- read_excel("tavid2000-2150.xls")
SUPEN_num <- as.data.frame(lapply(SUPEN, as.numeric), stringsAsFactors = FALSE)
ABC$Edad = 2023 - as.double(format(ABC$`Fecha de nacimiento`, format="%Y"))
```



```{r}

ABC[ABC$Sexo == 'M',]$Sexo <- '1'
ABC[ABC$Sexo == 'F',]$Sexo <- '2'
ABC$Sexo <- as.double(ABC$Sexo) 



# hacer un check de las qx por cada año por cada persona. Sumarlas todas. Ya entendí la dificultad de este ejercicio


```

```{r}
get_qx <- function(df_obs, df_prob){
  c <- 1
  all_qx = list()
  for (i in 1:length(df_obs[[1]])){
    x <- df_obs$Edad[i]
    if(i != 1) {
      if((df_obs$Edad[i-1] == x) & (df_obs$Sexo[i] == df_obs$Sexo[i-1])){
        
        all_qx[c] <- all_qx[c-1]
        c <- c+1
        next
      }
    } 
    y <- 2023
    df <- df_prob[df_prob$sex == df_obs$Sexo[i],]
    local_qx <- list()
    n <- 1
    while (any(df$edad == x & df$year == y)) {
      # Filtrar datos por edad y año actual 
      qx <- df[df$edad == x & df$year == y , ]$qx
      local_qx[n] <- 1 - qx
      n <- n + 1
      x <- x + 1
      y <- y + 1
    }
    all_qx[[c]] <- list()
    all_qx[[c]][[1]] <- local_qx
    all_qx[[c]][[2]] <- df_obs$Sexo[i] 
    all_qx[[c]][[3]] <- df_obs$Edad[i] 
    
    
    c <- c+1
  }
  
  return(all_qx)
}
```


```{r}
t <- proc.time()
qx <- get_qx(ABC, SUPEN_num)
proc.time() - t
```

```{r}
proy_per_viva <- data.frame(edad = 0:100, poblacionM = numeric(101), poblacionH = numeric(101))
proy_per_viva$poblacionH[1] = 272
proy_per_viva$poblacionM[1] = 228

proy_viva <- function(qx, df){
  acumH <- numeric(272) + 1
  acumM <- numeric(228) + 1
  for (i in 1:100){
    m <- 0
    h <- 0
    for (c in 1:500){
      if(qx[[c]][[2]] == 1){
        h <- h + 1
        if(i > length(qx[[c]][[1]])){
          next
        }        
        acumH[h] <- acumH[h]*qx[[c]][[1]][[i]]
      } else {
        m <- m +1
        if(i > length(qx[[c]][[1]])){
          next
        }         
        acumM[m] <- acumM[m]*qx[[c]][[1]][[i]]
      }
    }
    df$poblacionH[i+1] <- sum(acumH)
    df$poblacionM[i+1] <- sum(acumM)
  }
  return(df)
}

proy_per_viva <- proy_viva(qx, proy_per_viva)
proy_per_viva$poblacionM <- round(proy_per_viva$poblacionM, 8)
proy_per_viva$poblacionH <- round(proy_per_viva$poblacionH, 8)
```

```{r}
proy_emp <- data.frame(edad = 0:100, poblacionM = numeric(101), poblacionH = numeric(101))
proy_emp$poblacionH[1] = 272
proy_emp$poblacionM[1] = 228

proy_emp_vivos <- function(qx, df){
  acumH <- numeric(272) + 1
  acumM <- numeric(228) + 1
  for (i in 1:100){
    m <- 0
    h <- 0
    for (c in 1:500){
      if(qx[[c]][[2]] == 1){
        h <- h + 1
        if(i > length(qx[[c]][[1]])){
          next
        }
        if(65 <= qx[[c]][[3]] + i){
          acumH[h] <- 0
          next
        }        
        acumH[h] <- acumH[h]*qx[[c]][[1]][[i]]
      } else {
        m <- m +1
        if(i > length(qx[[c]][[1]])){
          next
        }     
        if(65 <= qx[[c]][[3]] + i){
          acumM[m] <- 0
          next
        } 
        acumM[m] <- acumM[m]*qx[[c]][[1]][[i]]
      }
    }
    df$poblacionH[i+1] <- sum(acumH)
    df$poblacionM[i+1] <- sum(acumM)
  }
  return(df)
}

proy_emp <- proy_emp_vivos(qx, proy_emp)
proy_emp$poblacionM <- round(proy_emp$poblacionM, 8)
proy_emp$poblacionH <- round(proy_emp$poblacionH, 8)
```


```{r}
proy_pen <- data.frame(edad = 0:100, poblacionM = numeric(101), poblacionH = numeric(101))
proy_pen_vivos <- function(qx, df){
  acumH <- numeric(272) + 1
  acumM <- numeric(228) + 1
  for (i in 1:100){
    m <- 0
    h <- 0
    penH <- numeric(272)
    penM <- numeric(228)
    for (c in 1:500){
      if(qx[[c]][[2]] == 1){
        h <- h + 1
        if(i > length(qx[[c]][[1]])){
          next
        }
        if(65 <= qx[[c]][[3]] + i){
          penH[h] <- 1
        }        
        acumH[h] <- acumH[h]*qx[[c]][[1]][[i]]
        penH[h] <- penH[h] * acumH[h]
      } else {
        m <- m +1
        if(i > length(qx[[c]][[1]])){
          next
        }     
        if(65 <= qx[[c]][[3]] + i){
          penM[m] <- 1
        } 
        acumM[m] <- acumM[m]*qx[[c]][[1]][[i]]
        penM[m] <- penM[m]*acumM[m]
      }
    }
    df$poblacionH[i+1] <- sum(penH)
    df$poblacionM[i+1] <- sum(penM)
  }
  return(df)
}
proy_pen <- proy_pen_vivos(qx, proy_pen)
proy_pen$poblacionM <- round(proy_pen$poblacionM, 8)
proy_pen$poblacionH <- round(proy_pen$poblacionH, 8)
```


```{r}
proy_dead_emp <- data.frame(edad = 0:100, poblacionM = numeric(101), poblacionH = numeric(101))

proy_emp_dead <- function(qx, df){
  acumH <- numeric(272) + 1
  acumM <- numeric(228) + 1
  for (i in 1:100){
    m <- 0
    h <- 0
    localH <- numeric(272)
    localM <- numeric(228)
    for (c in 1:500){
      if(qx[[c]][[2]] == 1){
        h <- h + 1
        if(i > length(qx[[c]][[1]])){
          next
        }
        if(65 <= qx[[c]][[3]] + i){
          acumH[h] <- 0
          next
        }        
        localH[h] <- acumH[h]*(1 - qx[[c]][[1]][[i]])
        acumH[h] <- acumH[h]*qx[[c]][[1]][[i]]
      } else {
        m <- m +1
        if(i > length(qx[[c]][[1]])){
          next
        }     
        if(65 <= qx[[c]][[3]] + i){
          acumM[m] <- 0
          next
        } 
        localM[m] <- acumM[m]*(1 - qx[[c]][[1]][[i]])
        acumM[m] <- acumM[m]*qx[[c]][[1]][[i]]
      }
    }
    df$poblacionH[i+1] <- sum(localH) + df$poblacionH[i]
    df$poblacionM[i+1] <- sum(localM) + df$poblacionM[i]
  }
  return(df)
}

proy_dead_emp <- proy_emp_dead(qx, proy_dead_emp)
proy_dead_emp$poblacionM <- round(proy_dead_emp$poblacionM, 8)
proy_dead_emp$poblacionH <- round(proy_dead_emp$poblacionH, 8)
```

```{r}
proy_dead_pen <- data.frame(edad = 0:100, poblacionM = numeric(101), poblacionH = numeric(101))
proy_pen_dead <- function(qx, df){
  acumH <- numeric(272) + 1
  acumM <- numeric(228) + 1
  for (i in 1:100){
    m <- 0
    h <- 0
    penH <- numeric(272)
    penM <- numeric(228)
    for (c in 1:500){
      if(qx[[c]][[2]] == 1){
        h <- h + 1
        if(i > length(qx[[c]][[1]])){
          next
        }
        if(65 <= qx[[c]][[3]] + i){
          penH[h] <- 1
        }        
        penH[h] <- penH[h] * acumH[h] *(1 - qx[[c]][[1]][[i]])
        acumH[h] <- acumH[h]*qx[[c]][[1]][[i]]
      } else {
        m <- m +1
        if(i > length(qx[[c]][[1]])){
          next
        }     
        if(65 <= qx[[c]][[3]] + i){
          penM[m] <- 1
        } 
        penM[m] <- penM[m]*acumM[m]*(1-qx[[c]][[1]][[i]])
        acumM[m] <- acumM[m]*qx[[c]][[1]][[i]]
      }
    }
    df$poblacionH[i+1] <- sum(penH) + df$poblacionH[i]
    df$poblacionM[i+1] <- sum(penM) + df$poblacionM[i]
  }
  return(df)
}
proy_dead_pen <- proy_pen_dead(qx, proy_dead_pen)
proy_dead_pen$poblacionM <- round(proy_dead_pen$poblacionM, 8)
proy_dead_pen$poblacionH <- round(proy_dead_pen$poblacionH, 8)
```


```{r}
proy_per_dead <- proy_per_viva
proy_per_dead$poblacionM <- 228 - proy_per_dead$poblacionM
proy_per_dead$poblacionH <- 272 - proy_per_dead$poblacionH
```


```{r}
proy_mujeres <- data.frame(
  edad = 0:100,
  proy_vivas = proy_per_viva$poblacionM,
  proy_muertas = proy_per_dead$poblacionM,
  proy_emp_vivas = proy_emp$poblacionM,
  proy_pen_vivas = proy_pen$poblacionM,
  proy_emp_muertas = proy_dead_emp$poblacionM,
  proy_pen_muertas = proy_dead_pen$poblacionM
)
```

```{r}
proy_hombres <- data.frame(
  edad = 0:100,
  proy_vivos = proy_per_viva$poblacionH,
  proy_muertos = proy_per_dead$poblacionH,
  proy_emp_vivos = proy_emp$poblacionH,
  proy_pen_vivos = proy_pen$poblacionH,
  proy_emp_muertos = proy_dead_emp$poblacionH,
  proy_pen_muertos = proy_dead_pen$poblacionH
)
```












